setup and doc pre-commit
pyfar/gallery pull request #11
Opened 2024-02-26 12:47 UTC by ahms5

closes #5

2024-02-26 13:03 UTC, f-brinkmann requested changes
Thanks, looks fine, I only had one comment.

2024-02-26 13:03 UTC, f-brinkmann commented on README.rst
> +   flake8 test must pass without any warnings for `./pyfar` and `./tests` using the default or a stricter configuration. Flake8 ignores `E123/E133, E226` and `E241/E242` by default. If necessary adju
I think, we don't need this here - or only for tests, once we have some.

2024-02-26 15:38 UTC, pingelit approved these changes

2024-02-26 16:04 UTC, pingelit requested changes
I just notices some errors.

2024-02-26 16:04 UTC, pingelit commented on README.rst
> +    $ pip install -r requirements_dev.txt
```suggestion
    $ pip install -r requirements.txt
```
I just noticed, the previous version does not work.

2024-02-26 16:15 UTC, pingelit commented
Thanks, I'm also getting a warning with the pre-commit:
```bash
[WARNING] The 'files' field in hook 'jupyter-nb-clear-output' is a regex, not a glob -- matching '/*' probably isn't what you want here
```
Are you getting this as well?

2024-02-26 17:56 UTC, mberz requested changes
I'm getting the same warning as @pingelit 

``` console
[WARNING] The 'files' field in hook 'jupyter-nb-clear-output' is a regex, not a glob -- matching '/*' probably isn't what you want here
jupyter-nb-clear-output..............................(no files to check)Skipped
```

It fails to clear notebooks with cell output for me since it's not detecting files properly.

Running nbconvert on the respective files manually works as expected.

2024-02-26 18:17 UTC, ahms5 commented
If you want to commit a notebook with outputs, it fails and delete the outputs, then you just need to add the changes and it works.


For more detail:
https://zhauniarovich.com/post/2020/2020-06-clearing-jupyter-output/

2024-02-27 12:40 UTC, f-brinkmann requested changes
Thanks, works for me as well. I would only suggest to add some information about the error that occurs, when trying to push a notebook including output.

2024-02-27 12:40 UTC, f-brinkmann commented on README.rst
> +6. Commit your changes and push your branch to GitHub::
Maybe add information about the pre-commit workflow:

'Note that the commit will fail if you are trying to commit notebooks including output. Trying to push will automatically remove the output in these notebooks after which they must be saved and the push can be done.'

2024-02-27 12:55 UTC, f-brinkmann approved these changes

2024-02-27 13:15 UTC, merged